---
apiVersion: v1
kind: Secret
metadata:
  name: tenant-secrets
  labels: {}
stringData:
  FEATURES_AGGREGATE_REPEAT_PEAT_REPEAT: "true"
  ENGINE_IO_DATA_GRIDFS_ENABLED: "true"
  ENGINE_IO_DATA_GRIDFS_COMPRESS: "true"
  AGENT_JOB_MAX_OUTPUT_SIZE: "20971520"
