---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: swimlane-tasks
  name: swimlane-tasks
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: swimlane-tasks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swimlane-tasks
    spec:
      containers:
      - env: []
        envFrom:
        - secretRef:
            name: tenant-secrets
            optional: false
        image: swimlane/swimlane-tasks
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        name: swimlane-tasks
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          requests:
            cpu: "500m"
            memory: "4096Mi"
          limits:
            memory: "4096Mi"
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsUser: 2000
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: swimlane-tasks
            tenant.swimlane.io/tenant-id: REPLACE_TENANT_ID
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
